CREATE TABLE hospital_hashes (
    hospital_id VARCHAR(50) PRIMARY KEY REFERENCES hospitals(hospital_id) ON DELETE CASCADE,
    hospital_hash TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
